package com.greenhouse.models;

import java.time.LocalDateTime;

/**
 * Represents a system alert generated by sensors or background threads.
 */
public class Alert {
    private int id;
    private String message;
    private AlertType type;
    private AlertSeverity severity;
    private boolean resolved;
    private LocalDateTime timestamp;

    public Alert(int id, String message, AlertType type, AlertSeverity severity) {
        this.id = id;
        this.message = message;
        this.type = type;
        this.severity = severity;
        this.resolved = false;
        this.timestamp = LocalDateTime.now();
    }

    public int getId() { return id; }
    public String getMessage() { return message; }
    public AlertType getType() { return type; }
    public AlertSeverity getSeverity() { return severity; }
    public boolean isResolved() { return resolved; }
    public LocalDateTime getTimestamp() { return timestamp; }

    public void resolve() {
        this.resolved = true;
    }
}
